### ISSUE TITLE
Error: spawn UNKNOWN on Windows job

### ISSUE THREAD

**Issue by dzid26** [tete1030/safe-debugger-action#2]
Error:
```
Run tete1030/safe-debugger-action@master
Error: spawn UNKNOWN
```

```
jobs:
  Build_Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Setup Debug Session
      uses: tete1030/safe-debugger-action@master
```
